/*
 * Curated Lucide icon registry (frontend side).
 *
 * Keys are Lucide icon names (kebab-case) and MUST stay in sync with the
 * backend source of truth at backend/config/icons.php. Each key maps to a
 * lucide-react component (imported explicitly so the bundle stays tree-shaken).
 */
import {
  Cog,
  Settings,
  Gauge,
  Zap,
  Power,
  Leaf,
  Mountain,
  Snowflake,
  Thermometer,
  Flame,
  Armchair,
  Key,
  Sun,
  Wind,
  Shield,
  ShieldCheck,
  Camera,
  Radar,
  Eye,
  Baby,
  Bluetooth,
  Smartphone,
  Navigation,
  Monitor,
  Usb,
  BatteryCharging,
  Music,
  Plug,
  Wifi,
  CloudSnow,
  Satellite,
  Route,
  MountainSnow,
  Users,
  Briefcase,
  Luggage,
  Package,
  Bike,
  Caravan,
  Truck,
  Dog,
  Umbrella,
  UserPlus,
  Fuel,
  Infinity,
  PhoneCall,
  Tent,
  Refrigerator,
  Map,
  Bed,
  Bath,
  ShowerHead,
  Tv,
  Utensils,
  Coffee,
  Microwave,
  WashingMachine,
  Wine,
  Waves,
  Dumbbell,
  Trees,
  DoorOpen,
  Lock,
  Car,
  Check,
  Star,
  Sparkles,
  Tag,
  Info,
  Clock,
  Plus,
} from 'lucide-react'

export const ICON_REGISTRY = {
  cog: Cog,
  settings: Settings,
  gauge: Gauge,
  zap: Zap,
  power: Power,
  leaf: Leaf,
  mountain: Mountain,
  snowflake: Snowflake,
  thermometer: Thermometer,
  flame: Flame,
  armchair: Armchair,
  key: Key,
  sun: Sun,
  wind: Wind,
  shield: Shield,
  'shield-check': ShieldCheck,
  camera: Camera,
  radar: Radar,
  eye: Eye,
  baby: Baby,
  bluetooth: Bluetooth,
  smartphone: Smartphone,
  navigation: Navigation,
  monitor: Monitor,
  usb: Usb,
  'battery-charging': BatteryCharging,
  music: Music,
  plug: Plug,
  wifi: Wifi,
  'cloud-snow': CloudSnow,
  satellite: Satellite,
  route: Route,
  'mountain-snow': MountainSnow,
  users: Users,
  briefcase: Briefcase,
  luggage: Luggage,
  package: Package,
  bike: Bike,
  caravan: Caravan,
  truck: Truck,
  dog: Dog,
  umbrella: Umbrella,
  'user-plus': UserPlus,
  fuel: Fuel,
  infinity: Infinity,
  'phone-call': PhoneCall,
  tent: Tent,
  refrigerator: Refrigerator,
  map: Map,
  bed: Bed,
  bath: Bath,
  'shower-head': ShowerHead,
  tv: Tv,
  utensils: Utensils,
  coffee: Coffee,
  microwave: Microwave,
  'washing-machine': WashingMachine,
  wine: Wine,
  waves: Waves,
  dumbbell: Dumbbell,
  trees: Trees,
  'door-open': DoorOpen,
  lock: Lock,
  car: Car,
  check: Check,
  star: Star,
  sparkles: Sparkles,
  tag: Tag,
  info: Info,
  clock: Clock,
  plus: Plus,
}

export const DEFAULT_ICON = 'check'

export function hasIcon(name) {
  return Boolean(name && ICON_REGISTRY[name])
}

/**
 * Renders a Lucide icon by its catalog name, falling back to a check mark
 * when the name is missing or unknown.
 */
export default function LucideIcon({ name, fallback = DEFAULT_ICON, ...props }) {
  const Icon = ICON_REGISTRY[name] || ICON_REGISTRY[fallback] || Check
  return <Icon {...props} />
}
